version: "3.1"

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "!123qweAs"
      MYSQL_DATABASE: "database_dev"
    ports:
      - "127.0.0.1:3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
